# copied from mind-of-rathewolf repo

# github pages hasn't updated to jekyll 4.0, which uses the theme's config file by default
# so, for now, you must copy the theme's config file's content into here

# ronv/sidey will likely be my main theme to start with...:
# it's quite bare, reads like an e-reader, yet has all the essentials
# one-page sites can use either the default theme minima or ronv/ultra
remote_theme: rahil627/sidey-customized # seems updated as of recently (01/2022), so try to fetch updats

# standard vars
title: marks of rathewolf
description: notes, *on everything*

# semi-standard vars
site: marks of rathewolf #often used by plguins
url: https://marks.rathewolf.com #used by plugins

  
# custom
# try to convert newlines properly
kramdown:
  input: GFM # ...already the default
  hard_wrap: true # todo: need to understand how this works
  
# theme specific vars
#twitter:
#  username: #yourusername
#  card: summary
#  creator: #yourusername
author:
#  twitter: #yourusername
  name: rahil627
#  avatar:
#  email: #youremail
  url: https://rathewolf.com 


# permalink: pretty

baseurl: ""

#highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

# note: remember to add to the gemfile too
plugins:
  # plugins that already exist on the github pages dependencies
  - jekyll-feed # i added to the gemfile anyway..

  # theme's custom plugins in the gemfile
  - jekyll-paginate # standard if not official plugin
  - jekyll-titles-from-headings

  # plugins that i added specifically for this project
  - 'jekyll-optional-front-matter'
  

# TESTING this bit
include:
  - /my-notes
  #- my-notes # cover all options
  #- /my-notes/
  
# this one is very important, as Jekyll by default only processes .md and .html files
# comment this out if you don't want to process txt files (basically all of my files)
markdown_ext: "txt, md" # does it override, or append? #error

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:name #/:slug

defaults:
   -
    scope:
      path: "" # empty string means all files, but a '.' would be more clear
    values:
      layout: "default" # i'm not sure how this works.., only works files with front matter, or with extension .md..?

# TESTING this bit
# this should add front-matter to site.static_files
   -
    scope:
      path: "my-notes" #or /my-notes?
      type: "" #if it has no type (doesn't have a markdown extension, and not explicitly given a type in the file)
    values: #add the following values to the front matter
      layout: "post"


# it might be better to stick to jekyll's defaults `_posts` 'n `_pages` for the sake of plugins 'n themes
#  -
#    scope:
#      path: "/posts"
#      type: posts
#    values:
#      layout: "post"

#  -
#    scope:
#      path: "pages"
#      type: pages
#    values:
#      layout: "page"
