source "https://rubygems.org"
gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
#gem 'jekyll-optional-front-matter'


gem 'jekyll-optional-front-matter', '0.3.2', git: 'https://github.com/rahil627/jekyll-optional-front-matter.git'
